import { Injectable } from '@nestjs/common';
import * as SocialPost from 'social-post-api';
import 'dotenv/config';

@Injectable()
export class AyrshareService {
  private social: SocialPost;

  constructor() {
    this.social = new SocialPost(process.env.AYRSHARE_API_KEY);
  }

  async addPicture(imageUrl: string, currentDate: string): Promise<string> {
    try {
      const postResponse = await this.social.post({
        // Required
        post: `Image imagined by #GPT4 based on recent trends on Twitter France (${currentDate}) and generated by #DALL·E 3`,

        /**
         * Required: Social media platforms to post.
         * Accepts an array of strings with values: "facebook", "twitter", "instagram", "linkedin", "youtube", "gmb", "reddit", or "telegram".
         * YouTube requires a video and not shown in the example. See https://docs.ayrshare.com/rest-api/endpoints/post#youtube
         */
        platforms: ['twitter', 'instagram'],

        // Optional: URLs of images or videos to include in the post
        mediaUrls: [`${imageUrl}`],
      });
      console.log('postResponse', postResponse);
      return postResponse;
    } catch (error) {
      console.error('Error while post:', error);
    }
  }
}
